table _MASCARA_FORMULAS
	lineageTag: fdf822e7-29e7-4252-a34b-bcd0cc10a4a1

	measure MEDIA_ANO_2_VAL =
			
			Var Mes = CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -12, MONTH))
			RETURN DIVIDE([Tempo_MAT_B_VAL],Mes)
		formatString: #,0.00
		displayFolder: 1º
		lineageTag: 28f230be-5b78-4028-8171-ad8334e6ca36

	measure Mes_12 =
			
			CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -12, MONTH))
			//IF([Tempo[VALOR]COUNT(mavi_prod_lj[mes])))
		formatString: 0
		displayFolder: 2º
		lineageTag: d6977565-ab8b-486d-8468-f4e3a8435ead

	measure MEDIA_ANO_1_VAL = ```
			
			VAR Ano = CALCULATE(max('PERIODO B'[ano_b]) - 1)
			VAR MES = CALCULATE(MAX('PERIODO B'[mes_b]))
			Var Cal = CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD('mavi_prod_lj'[dia], DATE(Ano,MES,1),-12,MONTH))
			RETURN DIVIDE([Tempo_MAT_A_VAL],Cal)
			
			```
		formatString: #,0.00
		displayFolder: 1º
		lineageTag: 8d04db6b-1884-48b7-a7fd-94f9835282ca

	measure MEDIA_ANO_1_QTD =
			
			VAR Ano = CALCULATE(max('PERIODO B'[ano_b]) - 1)
			VAR MES = CALCULATE(MAX('PERIODO B'[mes_b]))
			Var Cal = CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD('mavi_prod_lj'[dia], DATE(Ano,MES,1),-12,MONTH))
			RETURN DIVIDE([Tempo_MAT_A_QTD],Cal)
		displayFolder: 1º
		lineageTag: 4d024c76-aed0-4cb8-9f84-5c8957fe7bdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MEDIA_ANO_2_QTD =
			
			Var Mes = CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -12, MONTH))
			RETURN DIVIDE([Tempo_MAT_B_QTD],Mes)
		displayFolder: 1º
		lineageTag: def93e1b-15d9-4fd7-b0c3-fbf473f78996

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mes_3 =
			
			CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -3, MONTH))
			
			
			//IF([Tempo_TRI_B]=BLANK(),BLANK(),DISTINCTCOUNT(mavi_prod_lj[mes]))
		formatString: 0
		displayFolder: 2º
		lineageTag: 6bc4a006-0118-4c05-96f7-91fc04e3c020

	measure Mes_6 =
			
			CALCULATE(DISTINCTCOUNT(mavi_prod_lj[mes]), DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -6, MONTH))
		formatString: 0
		displayFolder: 2º
		lineageTag: 309e2e21-d120-4212-bf79-05c9a3bf92ef

	measure Ruptura = ```
			
			SWITCH(TRUE(),
			[Mes_3] = BLANK(), "RUPTURA",
			AND(AND([Mes_6]<=3,CALCULATE([Mes_6]=[Mes_12])),[Mes_3]<=3), "INOVACAO",
			"REGULAR")
			
			```
		displayFolder: 2º
		lineageTag: d0678585-c5f6-40dd-9dc5-1d3631f8e628

	measure PRECO_MEDIO_ANO_2 = [MEDIA_ANO_2_VAL]/[MEDIA_ANO_2_QTD]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: 3º
		lineageTag: 8133fa5c-009f-471f-a057-8501de71c082

	measure PARTICIPACAO_FAIR_SHARE = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR TT_VALOR = 
			SUMX(
			    ALL(mavi_produto),
			    [MEDIA_ANO_2_VAL]
			)
			
			VAR TT_QTD = SUMX(
			    ALL(mavi_produto),
			    [MEDIA_ANO_2_QTD]
			)
			VAR Rs = CALCULATE(([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds))
			RETURN 
			Rs
			
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: 4º
		lineageTag: f85ede8d-6f1c-4c67-b3c6-8e2ccb910baa

	measure VARIACAO_FAIR_SHARE =
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			return
			IFERROR((([MEDIA_ANO_2_VAL]/[MEDIA_ANO_1_VAL]-1)*Valores)+(([MEDIA_ANO_2_QTD]/[MEDIA_ANO_1_QTD]-1)*QTds),BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 4º
		lineageTag: 0993d265-2c00-4d6e-b911-726e98a9c73e

	measure CONTRIBUICAO_FAIR_SHARE = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_1_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			VAR VALOR = 
			    CALCULATE(
			        [MEDIA_ANO_2_VAL] - [MEDIA_ANO_1_VAL]
			    )
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_1_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			VAR SQTD = 
			    CALCULATE(
			        [MEDIA_ANO_2_QTD] - [MEDIA_ANO_1_QTD]
			    )
			VAR MEDIO = (VALOR/TT_VALOR*Valores)+(SQTD/TT_QTD*QTds)
			
			RETURN
			MEDIO
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4º
		lineageTag: 5958b6cd-5634-468c-8151-d43fc2ebf32d

	measure RANK = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			RETURN 
			    RANKX(
			        ALL(mavi_produto), 
			        CALCULATE(
			            CALCULATE([MEDIA_ANO_2_VAL]/TT_VALOR*Valores+[MEDIA_ANO_2_QTD]/TT_QTD*QTds), 
			            mavi_produto[sub_categoria] = SUBCATEGORIA
			        )
			    )
			
			```
		formatString: 0
		displayFolder: 4º
		lineageTag: ba79dcd2-e561-4cf4-bd94-ff09bd6327a3

	measure Top_80 =
			SWITCH(TRUE(),
			[TEORIA PARETO] <= 0.8, "TOP 80",
			[TEORIA PARETO] > 0.8, "BOT 20")
		displayFolder: 4º
		lineageTag: 2cb680cc-beaf-4332-adc5-77907759ff0d

	measure Top_50 =
			SWITCH(TRUE(),
			[TEORIA PARETO] <= 0.5, "TOP 50",
			[TEORIA PARETO] <= 0.7, "TOP 70",
			[TEORIA PARETO] <= 0.9, "TOP 90",
			"BOT 10")
		displayFolder: 4º
		lineageTag: aaf23731-fcb2-4666-8dd9-83eda6d55f92

	measure Top_80_segmento =
			SWITCH(TRUE(),
			or([TESTE_PARET_SEGMENTO] <= 0.8, [TESTE_RANK_SEGMENTO] = 1), "TOP 80",
			[TESTE_PARET_SEGMENTO] > 0.8, "BOT 20")
		displayFolder: 5º
		lineageTag: 2018a2ac-32d0-47dd-a843-9492e3df6bb4

	measure Top_50_SEGMENTO =
			SWITCH(TRUE(),
			[TESTE_PARET_SEGMENTO] <= 0.5, "TOP 50",
			[TESTE_PARET_SEGMENTO] <= 0.7, "TOP 70",
			[TESTE_PARET_SEGMENTO] <= 0.9, "TOP 90",
			"BOT 10")
		displayFolder: 5º
		lineageTag: f620df48-901b-4064-9407-ae40de3a3c59

	measure _ = BLANK()
		formatString: 0
		lineageTag: 99f5354a-cc53-4406-934a-57d89db08a92

	measure 'TESTE_PARTICIPAÇÃO SEGMENTO' = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			VAR SEGMENTO = SELECTEDVALUE(mavi_produto[segmento])
			VAR SUBSEGMENTO = SELECTEDVALUE(mavi_produto[sub_segmento])
			VAR RANGE = SELECTEDVALUE(mavi_produto[tamanho_range])
			VAR TIER = SELECTEDVALUE(mavi_produto[desc_c])
			
			
			VAR TT_ATUAL = 
			        [MEDIA_ANO_2_VAL]
			    
			
			
			VAR TT_SHARE = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR TT_ATUAL_Q = 
			        [MEDIA_ANO_2_QTD]
			
			
			VAR TT_SHARE_Q = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR PART = (TT_ATUAL / TT_SHARE*Valores)+(TT_ATUAL_Q/TT_SHARE_Q*QTds)
			
			RETURN
			PART
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 5º
		lineageTag: ab54a612-8ffe-42d5-a208-5a0058edca84

	measure TESTE_PARET_SEGMENTO = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			VAR SEGMENTO = SELECTEDVALUE(mavi_produto[segmento])
			VAR SUBSEGMENTO = SELECTEDVALUE(mavi_produto[sub_segmento])
			VAR RANGE = SELECTEDVALUE(mavi_produto[tamanho_range])
			VAR TIER = SELECTEDVALUE(mavi_produto[desc_c])
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR MEDIO = CALCULATE(([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds))
			
			
			VAR TBResumo = 
			CALCULATETABLE(
			    SUMMARIZE(
			        ALLSELECTED(mavi_prod_lj),
			        mavi_produto[Concat_ean_nome],
			        "TOTAL", CALCULATE(
			        ([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*Qtds),
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER
			    )
			    ), ALL(mavi_produto)
			)
			VAR ACUMULANDO = 
			    CALCULATE(SUMX(
			        FILTER(TBResumo, [TOTAL] >= MEDIO),[TOTAL]
			    ))
			
			RETURN
			ACUMULANDO
			
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 5º
		lineageTag: 56da9b99-51e4-4606-8818-0c8074ce4934

	measure TESTE_RANK_SEGMENTO = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			VAR SEGMENTO = SELECTEDVALUE(mavi_produto[segmento])
			VAR SUBSEGMENTO = SELECTEDVALUE(mavi_produto[sub_segmento])
			VAR RANGE = SELECTEDVALUE(mavi_produto[tamanho_range])
			VAR TIER = SELECTEDVALUE(mavi_produto[desc_c])
			
			
			
			VAR TT_SHARE = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			         mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			
			VAR TT_SHARE_Q = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			         mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR RANKING = 
			    RANKX(
			        ALL(mavi_produto), 
			            CALCULATE(
			                CALCULATE(([MEDIA_ANO_2_VAL] / TT_SHARE*Valores)+([MEDIA_ANO_2_QTD]/TT_SHARE_Q*QTds)), 
			                mavi_produto[sub_categoria] = SUBCATEGORIA,
			                mavi_produto[segmento] = SEGMENTO,
			                mavi_produto[sub_segmento] = SUBSEGMENTO,
			                mavi_produto[tamanho_range] = RANGE,
			                mavi_produto[desc_c] = TIER
			        )
			    )
			
			RETURN
			RANKING
			
			
			```
		formatString: 0
		displayFolder: 5º
		lineageTag: 39cb6827-ab7f-43ed-9d2f-6afca6470407

	measure PRECO_MEDIO_SUBCATEGORIA = ```
			
			
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			VAR SEGMENTO = SELECTEDVALUE(mavi_produto[segmento])
			VAR SUBSEGMENTO = SELECTEDVALUE(mavi_produto[sub_segmento])
			VAR RANGE = SELECTEDVALUE(mavi_produto[tamanho_range])
			VAR TIER = SELECTEDVALUE(mavi_produto[desc_c])
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        ALL(mavi_produto[Concat_ean_nome])
			    )
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[segmento] = SEGMENTO,
			        mavi_produto[sub_segmento] = SUBSEGMENTO,
			        mavi_produto[tamanho_range] = RANGE,
			        mavi_produto[desc_c] = TIER,
			        ALL(mavi_produto[Concat_ean_nome])
			    )
			VAR MEDIO = TT_VALOR/TT_QTD
			
			RETURN
			MEDIO
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: 3º
		lineageTag: 0f3d58dc-cf00-4d57-bd9e-5dd58441552d

	measure PRECO_MEDIO_FABRCANTE = ```
			
			
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			VAR FABRICANTE = SELECTEDVALUE(mavi_produto[fabricante])
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[FABRICANTE] = FABRICANTE,
			        ALL(mavi_produto[Concat_ean_nome])
			    )
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        mavi_produto[FABRICANTE] = FABRICANTE,
			        ALL(mavi_produto[Concat_ean_nome])
			    )
			VAR MEDIO = TT_VALOR/TT_QTD
			
			RETURN
			MEDIO
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: 3º
		lineageTag: d77fda86-9c6c-42a4-bd4d-730146f18f8d

	measure PARTICIPAÇAO_SUBCATEGORIA = ```
			
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR MEDIO = ([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds)
			
			RETURN
			MEDIO
			
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4º
		lineageTag: 70371109-3de0-42b2-ac47-28e164a389d3

	measure %PARETO_QTD =
			
			
			CALCULATE(
			    DISTINCTCOUNT(mavi_produto[Concat_EAN_NOME]),
			    FILTER(
			        ALL(mavi_produto[Concat_EAN_NOME]),
			        [TEORIA PARETO] <= 0.8
			    )
			)
		formatString: 0
		displayFolder: RESUMO
		lineageTag: b888bf43-1900-4070-b95a-9c6c59b4058f

	measure '%Participação Pareto' = DIVIDE([%PARETO_QTD],[%QTD_Produtos])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO
		lineageTag: 71baec63-7964-455a-8c4b-2f84c935a5f6

	measure %QTD_Produtos = CALCULATE(DISTINCTCOUNT(mavi_produto[Concat_EAN_NOME]), FILTER(mavi_produto,[MEDIA_ANO_2_VAL] <>BLANK()))
		formatString: 0
		displayFolder: RESUMO
		lineageTag: 9e3abfcb-7c9b-48c8-b931-8fb437325bb7

	measure '%DIFF PARETO' = 1-[%Participação Pareto]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO
		lineageTag: 90e769f8-1b81-45c1-91cf-5f79489bbdf0

	measure 'TEORIA PARETO' = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        REMOVEFILTERS(mavi_produto)
			    )
			
			VAR MEDIO = CALCULATE(([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds))
			
			
			VAR TBResumo = 
			CALCULATETABLE(
			    SUMMARIZE(
			        ALLSELECTED(mavi_prod_lj),
			        mavi_produto[Concat_ean_nome],
			        "TOTAL", CALCULATE(
			        ([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds),
			        mavi_produto[sub_categoria] = SUBCATEGORIA
			    )
			    ), ALL(mavi_produto)
			)
			VAR ACUMULANDO = 
			    CALCULATE(SUMX(
			        FILTER(TBResumo, [TOTAL] >= MEDIO),[TOTAL]
			    ))
			
			RETURN
			ACUMULANDO
			//SUMX(TBResumo, [TOTAL])
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4º
		lineageTag: a26d8db3-51cb-4f37-a0e3-c003378c317c

	measure 'Top 1 nome' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_produto[nome_produto]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] =1))
			```
		displayFolder: RESUMO TOP
		lineageTag: edfa27f3-aaa3-46f5-aae5-5c4af9456c7a

	measure 'Top 1 Image' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_imagem[binario_para_url]),
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 1))
			```
		displayFolder: RESUMO TOP
		lineageTag: 1c7e053e-cdf6-4422-bf0b-8651d5275744

	measure 'Top 1 pareto' = ```
			CALCULATE(
			    [_FAIR_SHARE], 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 1))
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: 3b38b099-06fa-409d-9f5a-1571bbbe25d1

	measure 'Top 2 pareto' = ```
			CALCULATE(
			    [_FAIR_SHARE], 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 2))
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: f5dc9c22-3d78-450e-a4ef-f419706b6d72

	measure 'Top 3 pareto' = ```
			CALCULATE(
			    [_FAIR_SHARE], 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 3))
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: eb3bab8a-ccf6-414b-9bd0-ea1724789d2b

	measure 'Top 4 pareto' = ```
			CALCULATE(
			    [_FAIR_SHARE], 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 4))
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: 0a77e2a2-c44d-4724-bb13-b7caa44178cb

	measure 'Top 5 pareto' = ```
			CALCULATE(
			    [_FAIR_SHARE], 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 5))
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: c01b55e2-3407-498f-afa9-e1734207a3aa

	measure 'Top 2 nome' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_produto[nome_produto]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 2))
			```
		displayFolder: RESUMO TOP
		lineageTag: 99c26202-949b-473d-893e-ae16dff8569c

	measure 'Top 3 nome' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_produto[nome_produto]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 3))
			```
		displayFolder: RESUMO TOP
		lineageTag: c893323b-2556-45db-a9db-548fe9fed536

	measure 'Top 4 nome' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_produto[nome_produto]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 4))
			```
		displayFolder: RESUMO TOP
		lineageTag: faf9167c-9fd4-4c9f-a8b1-9dd534b64723

	measure 'Top 5 nome' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_produto[nome_produto]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 5))
			```
		displayFolder: RESUMO TOP
		lineageTag: b11a8381-1369-4856-96be-0d2c6956f89b

	measure 'Top 2 Image' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_imagem[binario_para_url]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 2))
			```
		displayFolder: RESUMO TOP
		lineageTag: 3406aadd-afa3-41c8-8e64-ca0dbe959e63

	measure 'Top 3 Image' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_imagem[binario_para_url]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 3))
			```
		displayFolder: RESUMO TOP
		lineageTag: 5fe8d4f1-59f0-4372-adb3-07f48beda5ea

	measure 'Top 4 Image' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_imagem[binario_para_url]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 4))
			```
		displayFolder: RESUMO TOP
		lineageTag: ceb3d1ba-4af7-4943-9e9c-9eec5c48f7bc

	measure 'Top 5 Image' = ```
			CALCULATE(
			    SELECTEDVALUE(mavi_imagem[binario_para_url]), 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 5))
			```
		displayFolder: RESUMO TOP
		lineageTag: 0dcc5b2d-47bf-4a4a-8528-25bac467301e

	measure 'Top 3 rank' = 3
		formatString: 0
		displayFolder: RESUMO TOP
		lineageTag: ed55ec34-3e90-4df6-aa65-f86772cd92f7

	measure 'Top 2 rank' = 2
		formatString: 0
		displayFolder: RESUMO TOP
		lineageTag: 4ea50824-ad3e-409b-a395-afa97e617359

	measure 'Top 1 rank' = 1
		formatString: 0
		displayFolder: RESUMO TOP
		lineageTag: 74ef1ddb-b4d7-40f0-ab1f-7eaf25aa9537

	measure 'Top 4 rank' = 4
		formatString: 0
		displayFolder: RESUMO TOP
		lineageTag: d434d519-39b8-42ed-b827-55281410eaaa

	measure 'Top 5 rank' = 5
		formatString: 0
		displayFolder: RESUMO TOP
		lineageTag: 65891ed5-4645-4270-9b3e-0afb83ddbbeb

	measure %PARETO_QTD_20 = ```
			[%QTD_Produtos] -[%PARETO_QTD]
			
			```
		formatString: 0
		displayFolder: RESUMO
		lineageTag: 6cc06f1d-1031-455c-8b89-3491125f93ac

	measure 'VALOR 24 MESES' =
			
			Var Mes = CALCULATE([VALOR], DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -24, MONTH))
			RETURN  Mes
		displayFolder: TABELAO
		lineageTag: bee467b0-d5a2-4355-9709-5f15befedb76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD 24 MESES' =
			
			Var Mes = CALCULATE([QUANTIDADE], DATESINPERIOD(mavi_prod_lj[dia], MAX('PERIODO B'[data b]), -24, MONTH))
			RETURN  Mes
		displayFolder: TABELAO
		lineageTag: 8143272c-8181-4d7a-ae02-d4f953884c69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IS_MANTER = ```
			SWITCH(TRUE(),
			([Top_80_segmento] = "TOP 80"), "MANTER", 
			([Top_80_segmento] = "BOT 20") && [VARIACAO_FAIR_SHARE] > 0, "MANTER","REVISAR"
			)
			```
		displayFolder: 5º
		lineageTag: 8b1d381b-2449-476c-965e-696e313dd08c

	measure '_FAIR SHARE' = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR TT_V = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]),
			        ALLEXCEPT(mavi_produto, mavi_produto[sub_categoria])
			    )
			VAR TT_Q = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]),
			        ALLEXCEPT(mavi_produto, mavi_produto[sub_categoria])
			    )
			
			RETURN
			([MEDIA_ANO_2_VAL]/ TT_V * Valores)+([MEDIA_ANO_2_QTD]/ TT_Q * QTds)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1b9fd3ee-e053-484a-96f2-f01e07f500bb

	measure TEORIA_PARETO_OP = ```
			
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			
			VAR TT_VALOR = 
			    CALCULATE(
			        [MEDIA_ANO_2_VAL], 
			        mavi_produto[sub_categoria] = SUBCATEGORIA
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        [MEDIA_ANO_2_QTD], 
			        mavi_produto[sub_categoria] = SUBCATEGORIA
			    )
			
			VAR MEDIO = 
			    DIVIDE([MEDIA_ANO_2_VAL], TT_VALOR, 0) * 0.6 + 
			    DIVIDE([MEDIA_ANO_2_QTD], TT_QTD, 0) * 0.4
			
			VAR TBResumo = 
			    SUMMARIZE(
			        FILTER(
			            ALL(mavi_produto),
			            mavi_produto[sub_categoria] = SUBCATEGORIA
			        ),
			        mavi_produto[Concat_ean_nome],
			        "TOTAL", 
			        DIVIDE([MEDIA_ANO_2_VAL], TT_VALOR, 0) * 0.6 + 
			        DIVIDE([MEDIA_ANO_2_QTD], TT_QTD, 0) * 0.4
			    )
			
			VAR ACUMULANDO = 
			    SUMX(
			        FILTER(TBResumo, [TOTAL] >= MEDIO), 
			        [TOTAL]
			    )
			
			RETURN
			ACUMULANDO
			```
		displayFolder: TESTES
		lineageTag: a7ac7068-c4b7-4800-a655-0eac4181fe4d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% PRODUTO' =
			
			VAR TT = CALCULATE(CALCULATE(DISTINCTCOUNT(mavi_produto[Concat_EAN_NOME]),FILTER(mavi_produto,[MEDIA_ANO_2_VAL] <>BLANK())), ALL(mavi_produto[marca]))
			
			RETURN [%QTD_Produtos]/TT
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO
		lineageTag: 97d5189b-0d49-4dad-a6c0-35c3f4e003b3

	measure %FAIRSHARE_QTDPROD = [_FAIR SHARE]/[%QTD_Produtos]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO
		lineageTag: f0824627-4ea4-4e64-bd64-0443bf808662

	measure CD/G = ```
			SWITCH(TRUE(),
			([Top_80_segmento] = "TOP 80"), "MANTER", 
			[TEORIA PARETO] <= 0.7 && [VARIACAO_FAIR_SHARE] > 0, "MANTER","REVISAR"
			)
			```
		displayFolder: 5º
		lineageTag: 1cdb69c6-7782-4c5c-a39e-a84b23bc168d

	measure RANK_FAIR_SHARE = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        ALLSELECTED(mavi_produto)
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        ALLSELECTED(mavi_produto)
			    )
			
			RETURN 
			    RANKX(
			        ALLSELECTED(mavi_produto), 
			        CALCULATE(
			            CALCULATE([MEDIA_ANO_2_VAL]/TT_VALOR*Valores+[MEDIA_ANO_2_QTD]/TT_QTD*QTds)
			        )
			    )
			```
		formatString: 0
		displayFolder: RESUMO TOP
		lineageTag: 5822d587-62af-46ab-9e76-dfceba3cc5ab

	measure 'SOMA TOP 5 PARETO' = ```
			
			CALCULATE(
			    [TEORIA PARETO], 
			    FILTER(
			        VALUES(mavi_produto[Concat_EAN_NOME]), 
			        [RANK_FAIR_SHARE] = 5))
			```
		displayFolder: RESUMO TOP
		lineageTag: 14a7d844-cdfb-4cd4-88ab-f053a3b58aba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FAIR SHARE ACUMULADA' = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]), 
			        ALLSELECTED(mavi_produto)
			    )
			
			VAR TT_QTD = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]), 
			        ALLSELECTED(mavi_produto)
			    )
			
			VAR MEDIO = CALCULATE(([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds))
			
			
			VAR TBResumo = 
			CALCULATETABLE(
			    SUMMARIZE(
			        ALLSELECTED(mavi_prod_lj),
			        mavi_produto[Concat_ean_nome],
			        "TOTAL", CALCULATE(
			        ([MEDIA_ANO_2_VAL]/TT_VALOR*Valores)+([MEDIA_ANO_2_QTD]/TT_QTD*QTds)
			    )
			    ), ALLSELECTED(mavi_produto)
			)
			VAR ACUMULANDO = 
			    CALCULATE(SUMX(
			        FILTER(TBResumo, [TOTAL] >= MEDIO),[TOTAL]
			    ))
			
			RETURN
			ACUMULANDO
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: 272a4401-5027-46e6-b54d-80c491cb8b54

	measure _FAIR_SHARE = ```
			
			--------------------------------------------------
			VAR Valores = [ESCALA_FAIR_SHARE]
			VAR QTds =  1 - Valores
			--------------------------------------------------
			
			VAR TT_V = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_VAL]),
			        ALL(mavi_produto)
			    )
			VAR TT_Q = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_2_QTD]),
			        ALL(mavi_produto)
			    )
			
			RETURN
			([MEDIA_ANO_2_VAL]/ TT_V * Valores)+([MEDIA_ANO_2_QTD]/ TT_Q * QTds)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RESUMO TOP
		lineageTag: 6ad866da-c58b-44b7-b5fb-3ff2a3ca4722

	measure 'E1 CONTRIBUICAO_FAIR_SHARE' = ```
			
			
			VAR SUBCATEGORIA = SELECTEDVALUE(mavi_produto[sub_categoria])
			
			VAR TT_VALOR = 
			    CALCULATE(
			        SUMX(mavi_produto,[MEDIA_ANO_1_VAL]), 
			        mavi_produto[sub_categoria] = SUBCATEGORIA,
			        ALLSELECTED(mavi_produto)
			    )
			VAR VALOR = 
			    CALCULATE(
			        [MEDIA_ANO_2_VAL] - [MEDIA_ANO_1_VAL]
			    )
			// VAR TT_QTD = 
			//     CALCULATE(
			//         SUMX(mavi_produto,[MEDIA_ANO_1_QTD]), 
			//         mavi_produto[sub_categoria] = SUBCATEGORIA,
			//         REMOVEFILTERS(mavi_produto)
			//     )
			// VAR SQTD = 
			//     CALCULATE(
			//         [MEDIA_ANO_2_QTD] - [MEDIA_ANO_1_QTD]
			//     )
			VAR MEDIO = (VALOR/TT_VALOR*0.6)
			--+(SQTD/TT_QTD*0.4)
			
			RETURN
			TT_VALOR
			```
		displayFolder: 4º
		lineageTag: 06fc6e38-7400-4195-8248-6ab98b741475

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure E2 =
			
			CALCULATE(SUMX(mavi_produto,[MEDIA_ANO_1_VAL]), ALL(mavi_produto))
		displayFolder: 4º
		lineageTag: 5957d4d5-7c42-402f-9453-1de08a7b92de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ESCALA_FAIR_SHARE =
			
			VAR Selecao = SELECTEDVALUE(Selecao_FairShare[Selecao_FairShare Campos])
			RETURN
			SWITCH(Selecao,
			"60X40", 0.6,
			"50x50",0.5,
			"40X60",0.4,
			0.6)
		formatString: 0.00
		lineageTag: 2f35ba5f-7e5e-4185-9faa-819e07f52f59

	measure HTML_FEMSA =
			
			"
			<!DOCTYPE html>
			<html lang='pt-BR'>
			<head>
			    <meta charset='UTF-8'>
			    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			    <title>FEMSA Animação</title>
			    <link href='https://fonts.googleapis.com/css2?family=Nocturne+Serif+Black&display=swap' rel='stylesheet'>
			    <style>
			        body {
			            display: flex;
			            justify-content: center;
			            align-items: center;
			            height: 100vh;
			            margin: 0;
			            background-color: transparent;
			        }
			
			        .container {
			            font-family: 'Nocturne Serif Black', serif;
			            font-size: 50px;
			            font-weight: bold;
			            color: rgba(192,0,0,1); /* Cor das letras */
			            display: flex;
			        }
			
			        .letter {
			            opacity: 0;
			            animation: fadeIn 0.5s forwards;
			            font-size:80px;
			        }
			
			        .letter:nth-child(1) {
			            animation-delay: 0.5s;
			        }
			
			        .letter:nth-child(2) {
			            animation-delay: 1s;
			        }
			
			        .letter:nth-child(3) {
			            animation-delay: 1.5s;
			        }
			
			        .letter:nth-child(4) {
			            animation-delay: 2s;
			        }
			
			        .letter:nth-child(5) {
			            animation-delay: 2.5s;
			        }
			
			        @keyframes fadeIn {
			            to {
			                opacity: 1;
			            }
			        }
			    </style>
			</head>
			<body>
			    <div class='container'>
			        <div class='letter'>F</div>
			        <div class='letter'>E</div>
			        <div class='letter'>M</div>
			        <div class='letter'>S</div>
			        <div class='letter'>A</div>
			    </div>
			</body>
			</html>
			"
		lineageTag: 636af8ef-038b-4a50-aee1-75237602f899

	column Column
		isHidden
		formatString: 0
		lineageTag: 8e48e865-523d-4805-b13e-45328db37180
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _MASCARA_FORMULAS = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 42ed7475f75b4dd48bf40e30a0f44e9d

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

